### ISSUE TITLE
PHP 7.2 Object is special class name - Curl

### ISSUE THREAD

**Issue by mzglinski** [borodulin/yii2-helpers#1]
Hi!

Could you please change the base class for Curl class from Object to BaseObject, right now it is throwing compile error on PHP 7.2. Explanation below, thanks in advance!

https://github.com/unclead/yii2-multiple-input/issues/177

**Comment by borodulin** [comment]
https://github.com/borodulin/yii2-helpers/commit/fce7205b0e7f9d2673ddb21702ad858287ab8fa3
